org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
parchment_version=2023.09.03

mod_id=scylla
mod_name=Scylla
mod_license=All Rights Reserved
mod_version=1.0.3
mod_group_id=com.github.syren_dev_tech
mod_authors=ChrisOfNormandy
mod_description=A library mod for Minecraft modding.

geckolib_version=4.8.2