plugins {
    id 'java'
    id 'groovy'
    id 'net.minecraftforge.gradle' version '5.1.+' apply false
    id 'fabric-loom' version "${loom_version}" apply false
    id 'maven-publish'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

def isForge = project.findProperty('forge') == 'true'
def isFabric = project.findProperty('fabric') == 'true'

// Print what we're using
println "Using Forge: $isForge"
println "Using Fabric: $isFabric"

if (isForge) {
    apply plugin: 'net.minecraftforge.gradle'

    dependencies {
        minecraft 'net.minecraftforge:forge:1.20.1-47.1.0'
    }

    minecraft {
        mappings channel: 'official', version: '1.20.1'
        runs {
            client {
                workingDirectory project.file('run')
                property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
                property 'forge.logging.console.level', 'debug'
            }
        }
    }
}

if (isFabric) {
    apply plugin: 'fabric-loom'

    dependencies {
        minecraft "com.mojang:minecraft:${minecraft_version}"
        mappings "net.fabricmc:yarn:${yarn_mappings_version}:v2"
        modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    }

    loom {
        runs {
            client {
                property 'fabric.debug', 'true'
            }
        }
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.minecraftforge.net' }
    maven { url 'https://maven.fabricmc.net/' }
}